# Mean Normalization

In machine learning we use large amounts of data to train our models. Some machine learning algorithms may require that the data is *normalized* in order to work correctly. The idea of normalization, also known as *feature scaling*, is to ensure that all the data is on a similar scale, *i.e.* that all the data takes on a similar range of values. For example, we might have a dataset that has values between 0 and 5,000. By normalizing the data we can make the range of values be between 0 and 1.

In this lab, you will be performing a different kind of feature scaling known as *mean normalization*. Mean normalization will scale the data, but instead of making the values be between 0 and 1, it will distribute the values evenly in some small interval around zero. For example, if we have a dataset that has values between 0 and 5,000, after mean normalization the range of values will be distributed in some small range around 0, for example between -3 to 3. Because the range of values are distributed evenly around zero, this guarantees that the average (mean) of all elements will be zero. Therefore, when you perform *mean normalization* your data will not only be scaled but it will also have an average of zero. 

# To Do:

You will start by importing NumPy and creating a rank 2 ndarray of random integers between 0 and 5,000 (inclusive) with 1000 rows and 20 columns. This array will simulate a dataset with a wide range of values. Fill in the code below

In [16]:
# import NumPy into Python
import numpy as np

# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X = np.random.randint(0, 5001, (1000, 20))
# print the shape of X
print(X)


[[ 835 3579 3116 ... 2113 3978 4989]
 [ 143 4137 1566 ... 4094 4000 1341]
 [4782  729 2805 ...  669 3588 3057]
 ...
 [4092 3190 2744 ... 2144 1513  870]
 [3790 1262 3530 ... 3121 3705 1716]
 [ 413 4306 2888 ...  885 1186  785]]


Now that you created the array we will mean normalize it. We will perform mean normalization using the following equation:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. In other words, mean normalization is performed by subtracting from each column of $X$ the average of its values, and then by dividing by the standard deviation of its values. In the space below, you will first calculate the average and standard deviation of each column of $X$. 

In [22]:
# Average of the values in each column of X
ave_cols = X.mean(axis=0)

# Standard Deviation of the values in each column of X
std_cols = X.std(axis=0)

If you have done the above calculations correctly, then `ave_cols` and `std_cols`, should both be vectors with shape `(20,)` since $X$ has 20 columns. You can verify this by filling the code below:

In [24]:
# Print the shape of ave_cols
print(ave_cols)

# Print the shape of std_cols
print(std_cols)

[2435.071 2480.47  2619.509 2515.467 2477.28  2507.947 2416.009 2581.647
 2488.283 2491.244 2452.17  2505.564 2486.74  2470.406 2480.487 2522.169
 2536.677 2482.655 2498.998 2399.825]
[1427.08038315 1468.9399903  1437.97041135 1422.966352   1419.17817049
 1424.24067495 1419.74603466 1425.11869835 1428.1893204  1436.99333487
 1410.23777821 1461.82895576 1424.45026112 1479.60706242 1455.024564
 1415.32097153 1452.80773355 1447.37048401 1476.74352411 1451.24551278]


You can now take advantage of Broadcasting to calculate the mean normalized version of $X$ in just one line of code using the equation above. Fill in the code below

In [29]:
# Mean normalize X
X_norm = X / np.linalg.norm(X, ord=2, axis=1, keepdims=True)

If you have performed the mean normalization correctly, then the average of all the elements in $X_{\tiny{\mbox{norm}}}$ should be close to zero, and they should be evenly distributed in some small interval around zero. You can verify this by filing the code below:

In [42]:
# Print X_norm
print("Values of X_norm: ")
print(X_norm)
# Print the average of all the values of X_norm
print("\nAverage of all the values of X_norm: ")
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm
print("\nAverage of all the minimum values in each column of X_norm: ")
print(X_norm.min(axis=1))

# Print the average of the maximum value in each column of X_norm
print("\nAverage of the maximum value in each column of X_norm")
print(X_norm.max(axis=1))

Values of X_norm: 
[[0.05654527 0.24236591 0.21101207 ... 0.14309002 0.26938575 0.33784955]
 [0.01176686 0.34041597 0.12885942 ... 0.33687769 0.32914283 0.11034513]
 [0.39782793 0.06064755 0.23335578 ... 0.05565598 0.29849574 0.25432036]
 ...
 [0.29717536 0.23166896 0.19927888 ... 0.15570478 0.10987935 0.06318244]
 [0.2710291  0.09024768 0.25243607 ... 0.22318781 0.26495061 0.12271397]
 [0.03395842 0.35405558 0.23746227 ... 0.07276804 0.0975174  0.06454567]]

Average of all the values of X_norm: 
0.19412068804078803

Average of all the minimum values in each column of X_norm: 
[1.52367506e-02 1.17668562e-02 2.41259095e-03 1.40664823e-02
 1.58397244e-02 1.77849711e-03 4.31686901e-02 6.30676592e-03
 1.27329347e-03 2.59448870e-03 4.55848019e-04 4.79995133e-02
 2.68321191e-03 2.53337858e-03 1.77512525e-02 5.78389397e-02
 1.29543236e-03 1.01673723e-02 5.12456037e-02 3.33846162e-03
 6.76967992e-03 1.40983648e-02 2.67248558e-02 3.24442229e-02
 3.21783774e-02 1.65198150e-02 1.04332529e-02 4.47

You should note that since $X$ was created using random integers, the above values will vary. 

# Data Separation

After the data has been mean normalized, it is customary in machine learnig to split our dataset into three sets:

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The dataset is usually divided such that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. 

In this part of the lab you will separate `X_norm` into a Training Set, Cross Validation Set, and a Test Set. Each data set will contain rows of `X_norm` chosen at random, making sure that we don't pick the same row twice. This will guarantee that all the rows of `X_norm` are chosen and randomly distributed among the three new sets.

You will start by creating a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this by using the `np.random.permutation()` function. The `np.random.permutation(N)` function creates a random permutation of integers from 0 to `N - 1`. Let's see an example:

In [82]:
# We create a random permutation of integers 0 to 4
#np.random.permutation(55)
row_indices = np.random.permutation(10)
print(row_indices)
print(row_indices[0:2])
print(row_indices[2:7])
print(row_indices[8:])

[7 9 3 1 2 4 5 6 0 8]
[7 9]
[3 1 2 4 5]
[0 8]


# To Do

In the space below create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`. You can do this in one line of code by extracting the number of rows of `X_norm` using the `shape` attribute and then passing it to the  `np.random.permutation()` function. Remember the `shape` attribute returns a tuple with two numbers in the form `(rows,columns)`.

In [83]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])
print(type(row_indices))

<class 'numpy.ndarray'>


Now you can create the three datasets using the `row_indices` ndarray to select the rows that will go into each dataset. Rememeber that the Training Set contains 60% of the data, the Cross Validation Set contains 20% of the data, and the Test Set contains 20% of the data. Each set requires just one line of code to create. Fill in the code below

In [91]:
#Credits to Divakar @https://stackoverflow.com/questions/55662700/whats-the-most-efficient-way-to-split-up-a-numpy-ndarray-using-percentage/55663192#55663192
# Make any necessary calculations.
# You can save your calculations into variables to use later.
p = np.array([0.6,0.2,0.2])

# Create a Training Set
X_train, X_crossVal, X_test = np.split(row_indices,(len(row_indices)*p[:-1].cumsum()).astype(int))


If you performed the above calculations correctly, then `X_tain` should have 600 rows and 20 columns, `X_crossVal` should have 200 rows and 20 columns, and `X_test` should have 200 rows and 20 columns. You can verify this by filling the code below:

In [92]:
# Print the shape of X_train
print(X_train.shape)

# Print the shape of X_crossVal
print(X_crossVal.shape)

# Print the shape of X_test
print(X_test.shape)

(600,)
(200,)
(200,)
